/**
 * Maps response codes from database services and controllers to relevant HTTP status.
 */
export const stMap = {
    "SUCCESS": 200,
    "SUCCESS_REDUNDANT": 200,
    "NULL_PARAMETER": 400,
    "INVALID_CREDENTIALS": 401,
    "INVALID_ACCESS_TOKEN": 401,
    "REFRESH_TOKEN_INVALID": 401,
    "REFRESH_TOKEN_REUSE": 401,
    "REFRESH_TOKEN_REVOKED": 401,
	"NOT_IN_CHATROOM": 403,
	"INVALID_FRIENDSHIP_CODE": 403,
    "NOT_OWNER_OF_FRIENDSHIP_CODE": 403,
    "NOT_FOUND": 404,
    "UUID_COLLISION": 409,
    "LOGIN_IN_USE": 409,
    "BEFRIENDING_SELF": 409,
}